version: 2
references:
  workspace_root: &workspace_root
     ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  npm_cache_keys: &npm_cache_keys
    keys:
      - npm-cache-{{ checksum "package.json" }}-v1

  cache_npm_cache: &cache_npm_cache
    save_cache:
      key: npm-cache-{{ checksum "package.json" }}-v1
      paths:
        - ./node_modules/

  restore_npm_cache: &restore_npm_cache
    restore_cache:
      <<: *npm_cache_keys

jobs:
  build:
    working_directory: ~/project/build
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Install project dependencies
          command: npm install
      - *cache_npm_cache
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build
  test:
    working_directory: ~/project/build
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Run tests
          command: npm test
  deploy:
    working_directory: ~/project/build
    docker:
      - image: circleci/node:lts
    steps:
      - *attach_workspace
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master